{% set version = "1.12.0" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/releases/download/v1.12.0/firecrown-1.12.0-fixed.tar.gz
  sha256: 07fe9f9723136f171223e54145daaaa3ff5a760d8c455e22fa85a092bf695633

build:
  skip: true  # [win or py<311]
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - charset-normalizer
    - clmm
    - cosmosis >=3.0.0
    - cosmosis-build-standard-library
    - cython
    - dill
    - fitsio
    - fuzzywuzzy
    - getdist
    - idna
    - matplotlib-base
    - more-itertools
    - numcosmo >=0.21.1
    - numpy >=2.0
    - portalocker
    - pybobyqa
    - pyccl >=2.8.0
    - pydantic
    - python
    - pyyaml
    - requests
    - rich
    - sacc >=2.1
    - scipy >=1.12
    - tabulate
    - typer
    - types-pyyaml
    - urllib3

test:
  imports:
    - firecrown

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: DESC Cosmology Likelihood Framework

extra:
  recipe-maintainers:
    - marcpaterno
    - vitenti
    - beckermr
