{% set version = "1.2.0" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/archive/v{{ version }}.tar.gz
  sha256: c141625fc9196925f9aa1324938e48259febf0beeef37d19357efaa489de96e8

build:
  skip: true  # [win or py<38]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - pyccl
    - numpy
    - scipy
    - sacc

test:
  imports:
    - firecrown

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: DESC Cosmology Likelihood Framework

extra:
  recipe-maintainers:
    - marcpaterno
    - vitenti
    - beckermr
