{% set version = "0.5" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/archive/v{{ version }}.tar.gz
  sha256: a98ca4e37f73192a45396fa0089563bd54861ca9625738a06df4dab7e44fd107

build:
  skip: true  # [win]
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyccl >=2.0,<3
    - numpy
    - pyyaml
    - scipy
    - click
    - jinja2
    - sacc >=0.4.5,<0.5
    - cosmosis-standalone >=0.2.2

test:
  imports:
    - firecrown

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: constraints rock | the "c" is for cosmology

extra:
  recipe-maintainers:
    - beckermr
