{% set version = "1.7.2" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/archive/v{{ version }}.tar.gz
  sha256: b915d6744c1106e02ff8c8d198020722dd28046088284ec2c22b4ee4fe41f326

build:
  skip: true  # [win or py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - charset-normalizer
    - cosmosis >=3.0.0
    - cosmosis-build-standard-library
    - coverage
    - cython <3.0.0
    - dill
    - fitsio
    - flake8
    - fuzzywuzzy
    - getdist
    - idna
    - matplotlib-base
    - more-itertools
    - mypy
    - numcosmo >=0.21.1
    - numpy >=1.23.0
    - portalocker
    - pybobyqa
    - pyccl >=2.8.0
    - pyyaml
    - requests
    - sacc >=0.11
    - scipy
    - types-pyyaml
    - urllib3

test:
  imports:
    - firecrown

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: DESC Cosmology Likelihood Framework

extra:
  recipe-maintainers:
    - marcpaterno
    - vitenti
    - beckermr
    - mattkwiecien
