{% set version = "1.1.0" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/archive/v{{ version }}.tar.gz
  sha256: 26c0f8ce983cc04e5719ed21138f86f825b1007ca1c57fe3b71ee6b2ceb56303

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python >=3.8
    - pyccl
    - numpy
    - scipy
    - sacc

test:
  imports:
    - firecrown

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: DESC Cosmology Likelihood Framework

extra:
  recipe-maintainers:
    - vitenti
    - beckermr
